### PR TITLE
Change in the choice options. When the field type was dropdown. If th…

### PR DESCRIPTION
**Pull request by killianrochet**
…e choices were empty, then the conversion returned an error.

Modifications to the checkboxes. It was impossible to select multiple checkboxes

The solution is to initialise the list of choices, if there are no choices then the list will contain an empty string otherwise it will contain the choices. For checkboxes the solution is to create a checkbox field for each choice

### CODE REVIEW

**Comment by killianrochet** [comment]
@JuliaSprenger I have started to make changes, for the error with dropdowns and checkboxes

**Comment by JuliaSprenger** [comment]
Hi @killianrochet Is this PR still in progress or deprecated?

**Comment by killianrochet** [comment]
@JuliaSprenger yes, this PR is old, remember when we want to find a solution with multiple checkbox

**Comment by JuliaSprenger** [comment]
So this is not going to be merged. I will close it.

**Pull request closed without merging**
